module.exports = [
  'become a porn star',
  'get beaten up',
  'go to jail',
  'start an illegal business',
  'become a millionaire',
  'set the kitchen on fire while cooking',
  'become a comedian',
  'get married first',
  'become a monk or nun',
  'get admitted to a psych ward',
  'become a criminal',
  'get the most cliche tattoo',
  'steal someones partner',
  'tell false stories to get attention',
  'finish the food on everyone else\'s plate',
  'help someone bury a body',
  'have a one night stand',
  'be single forever',
  'get arrested for being to drunk',
  'throw up from drinking',
  'become an alcoholic',
  'become a gang member',
  'become miss universe',
  'die first',
  'have plastic surgery',
  'leave their keys in the car',
  'get a guiness world record',
  'be late to their own wedding',
  'date two people at once',
  'become best friends with an animal',
  'marry an inanimate object',
  'live the longest',
  'become the president/prime minister',
  'get arrested for public nudity',
  'fall in love with their best mate',
  'get asked for id at 35',
  'go skinny dipping in the sea',
  'have a weird fetish',
  'join the mile high club',
  'hire an escort',
  'still live with their parents at 30',
  'marry someone for a visa',
  'survive a zombie apocalypse',
  'become a groupie',
  'become a stalker',
  'haunt someone when they die',
  're-invent themselves after a breakup',
  'drink their own pee for the health benefits',
  'to marry someone but not love them',
  'cheat on their partner',
  'move to mars',
  'catfish someone',
  'get friend-zoned by everyone they date',
  'start their own cult/religion',
  'elope with a stranger',
  'build a sex dungeon',
  'accidently kill someone',
  'have the most children',
  'become a sugar daddy/mummy',
  'buy a sex robot',
  'become a youtuber',
  'bribe a police officer',
  'win the lottery and go into debt after a year',
  'live in a cabin in the middle of the woods',
  'win a nobel prize',
  'die a stupid death',
  'fail an std test',
  'win an olympic medal',
  'invent something useful',
  'stop washing themselves',
  'appear on a reality tv show',
  'cure world hunger',
  'sabotage someone else\'s relationship',
  're-gift something that was gifted to them',
  'get the whole gang in trouble',
  'go to a party just for the food',
  'sleep their way to the top',
  'fake their own death',
  'have a secret life',
  'win at an eating contest',
  'light up a room as soon as they enter',
  'embarrass themselves in front of a crush',
  'be catfished',
  'date someone for their money',
  'go viral online',
  'end up homeless',
  'become a drug dealer',
  'cancel plans at the last minute',
  'throw a fit during a game of monopoly',
  'end up in a car accident',
  'try out every diet option',
  'wear socks with sandals',
  'forget to eat',
  'forget that they made plans',
  'be a strict parent',
];
